from pathlib import Path

path = Path(r'D:\project\roadhelp\src\pages\GetHelp.tsx')
text = path.read_text(encoding='utf-8')
text = text.replace("import { formatCurrency, getServiceLabel } from '@/lib/utils';", "import { formatCurrency, getServiceLabel } from '@/lib/utils';\nimport { SERVICE_MAP } from '@/lib/constants';")
text = text.replace("  const currentService = selectedService ?? activeServices.find((service) => service.id === resolvedServiceType) ?? null;\n  const selectedServiceLabel = serviceLabelOverride || (currentService?.id === 'other' ? 'Other Services' : currentService ? getServiceLabel(currentService.id) : 'No service selected yet');", "  const currentService = selectedService ?? activeServices.find((service) => service.id === resolvedServiceType) ?? null;\n  const fallbackService = resolvedServiceType ? SERVICE_MAP[resolvedServiceType as ServiceType] : null;\n  const selectedServiceConfig = currentService ?? fallbackService;\n  const selectedServiceLabel = serviceLabelOverride || (selectedServiceConfig?.id === 'other' ? 'Other Services' : selectedServiceConfig ? getServiceLabel(selectedServiceConfig.id) : 'No service selected yet');")
text = text.replace("    if (!resolvedServiceType || !selectedLocation) return;", "    if (!selectedServiceConfig || !selectedLocation) return;")
text = text.replace("        serviceIcon: currentService.icon,\n        serviceBasePrice: currentService.basePrice,\n        serviceMaxPrice: currentService.maxPrice,", "        serviceIcon: selectedServiceConfig.icon,\n        serviceBasePrice: selectedServiceConfig.basePrice,\n        serviceMaxPrice: selectedServiceConfig.maxPrice,")
text = text.replace("        estimatedPrice: currentService.basePrice,", "        estimatedPrice: selectedServiceConfig.basePrice,")
text = text.replace("{currentService && (", "{selectedServiceConfig && (")
text = text.replace("<IconRenderer name={currentService.icon} size={24} />", "<IconRenderer name={selectedServiceConfig.icon} size={24} />")
text = text.replace("<span className=\"font-black text-sm\">{formatCurrency(currentService.basePrice)}+</span>", "<span className=\"font-black text-sm\">{formatCurrency(selectedServiceConfig.basePrice)}+</span>")
text = text.replace("{currentService ? <IconRenderer name={currentService.icon} size={24} /> : <Sparkles className=\"w-6 h-6\" />}", "{selectedServiceConfig ? <IconRenderer name={selectedServiceConfig.icon} size={24} /> : <Sparkles className=\"w-6 h-6\" />}")
text = text.replace("{currentService ? <IconRenderer name={currentService.icon} size={28} /> : <Sparkles className=\"w-7 h-7\" />}", "{selectedServiceConfig ? <IconRenderer name={selectedServiceConfig.icon} size={28} /> : <Sparkles className=\"w-7 h-7\" />}")
text = text.replace("{currentService ? estimateArrival(currentService) : 'Estimated arrival'}", "{selectedServiceConfig ? estimateArrival(selectedServiceConfig) : 'Estimated arrival'}")
text = text.replace("{currentService ? formatCurrency(currentService.basePrice) : 'N/A'}+", "{selectedServiceConfig ? formatCurrency(selectedServiceConfig.basePrice) : 'N/A'}+")
text = text.replace("{currentService ? estimateArrival(currentService) : 'Estimated arrival'}", "{selectedServiceConfig ? estimateArrival(selectedServiceConfig) : 'Estimated arrival'}")
path.write_text(text, encoding='utf-8')
